### ISSUE TITLE
It seems that some files missing and unable to run...

### ISSUE THREAD

**Issue by ToSev7en** [wenhuchen/HDSA-Dialog#1]
Hi Wenhu Chen ! ☺️ Thank you for sharing your awesome code of HDSA model ! 

But when I run the whole project, some errors occured. The error information shows below.

```python
Traceback (most recent call last):
  File "train_generator.py", line 23, in <module>
    from evaluator import evaluateModel
  File "/HDSA-Dialog/evaluator.py", line 6, in <module>
    from preprocessing.utils.dbPointer import queryResultVenues
  File "/HDSA-Dialog/preprocessing/utils/dbPointer.py", line 12, in <module>
    conn = sqlite3.connect(db)
sqlite3.OperationalError: unable to open database file
```

**It seems that a file named `dbPointer.py` which located at `/HDSA-Dialog/preprocessing/utils/dbPointer.py` contains some bugs.** 

I found `line 11` in `dbPointer.py` hard codes a db file which can not be found in this project.

Code in `line 11` showed below.

```python
db = '/mnt/sshd/wenhuchen/multiwoz/db/{}-dbase.db'.format(domain)
```
**This issue could be fix by modifying the db path to:**
```python
db = 'processing/db/{}-dbase.db'.format(domain)
```

Besides,  in `evaluator.py line 45` 

```python
fin1 = open('/mnt/sshd/wenhuchen/multiwoz/data/multi-woz/delex.json')
```

**I found that the `delex.json` is no where to find. And how to generate it?**

Look forward to your reply. Thank you!

**Comment by ToSev7en** [comment]
Oaky, I think I've already know how to generate `delex.json` ! 😁

**Comment by wenhuchen** [comment]
Thanks a lot for your feedback, I have already updated the repo. You can simply use the collect_data.sh to receive the delex.json. 

If you have some further questions, do not hesitate to ask me. Thanks!
