### ISSUE TITLE
about Pytorch-pretrained-BERT

### ISSUE THREAD

**Issue by scutcyr** [wenhuchen/HDSA-Dialog#11]
Could the authors tell us about the version of Pytorch-pretrained-BERT used in the code? Something wrong with 
`from pytorch_pretrained_bert.optimization import BertAdam, WarmupLinearSchedule`
the output is:
`ImportError: cannot import name 'WarmupLinearSchedule'`

**Comment by wenhuchen** [comment]
Here is the version I used:
```
>>> import pytorch_pretrained_bert
>>> pytorch_pretrained_bert.__version__
'0.6.2'
```
