### ISSUE TITLE
IndexError: index 23111876306094 is out of bounds for dimension 0 with size 2

### ISSUE THREAD

**Issue by Ner0oooooo** [wenhuchen/HDSA-Dialog#13]
Great work!
I ran into some problems when I ran tests.It doesn't always happen, it happens occasionally.It happen in Beam.py
    
    hyp.append(self.next_ys[j+1][k])                                                                          
IndexError: index 23111876306094 is out of bounds for dimension 0 with size 2
My pytorch version is 1.0.1  and python version is 3.6
Why do I encounter this situation? How can I solve it

**Comment by wenhuchen** [comment]
This could be due to the version mismatch.
