### ISSUE TITLE
Confused about the BERT-based dialog act predictor

### ISSUE THREAD

**Issue by 594zyc** [wenhuchen/HDSA-Dialog#2]
Thanks for your open-source code.
I have a question about the BERT-based dialog act predictor defined in train_predictor.py. It seems that the input of the next system DA predictor is the concatenation of the user utterance, the previous system response and database entry of each **single turn**.  This setting ignores the belief state as well as the dialog history, which is not consistent with the description of dialog act predictor in section 4 of the paper. It's confusing to me why the model can predict suitable dialog acts given such inadequate information.  Is this the case or I've misunderstood the code?  Looking forward to your explanation. 
Thanks a lot.

**Comment by wenhuchen** [comment]
Hi there, thanks for your interest in my code. You raised a very good question, I actually implemented several different versions of BERT-base models to leverage the database information and history into the DA prediction. But my preliminary conclusion (I might be wrong) is that "leveraging too long history does not help at all", the dialog act seems to be only relevant to the most recent turn. Secondly, the database is sometimes super huge, containing thousands of entries, like hotel and train domain, it is not easy to encode the whole database into the BERT encoder. You can visualize the current act prediction, the results seem quite reasonable. 

Anyway, I agree with your opinion, there is still a lot of research space the DA prediction (like how to leverage the structured information available at hand). If you have any thoughts, I'm more than happy to discuss with you.
