### ISSUE TITLE
Entity Matches : 16.90%  Requestable Success : 15.30%

### ISSUE THREAD

**Issue by InitialBug** [wenhuchen/HDSA-Dialog#6]
I have cloned the code and downloaded the pre-trained model, but the model only gets Entity Matches : 16.90%  Requestable Success : 15.30%.   But the  bleu (0.235) and entity F1 (0.657) is consistent with the paper, I'm confused with the preoblem.

**Comment by wenhuchen** [comment]
Hi, the database file was somehow broken, which leads to the problem. I just fix the problem, you can pull and try again. It should be fine by now.

**Comment by InitialBug** [comment]
Everything is OK. Thanks a lot.
