### ISSUE TITLE
请问下disentangle这个词在这篇文章里通俗易懂的意思该怎么理解啊？

### ISSUE THREAD

**Issue by guotong1988** [wenhuchen/HDSA-Dialog#7]
在这篇文章里，具体是模型的怎样的设计？
有没有disentangled representation相关的意思？
多谢！！！
多谢！！！
多谢！！！
@wenhuchen

**Comment by wenhuchen** [comment]
中文就是解耦合吧，把相互关联的高维度的向量拆分出来不同的部分表述不同的含义。其中一部分改变不会影响另一部分，这样就达到了一个控制的效果。
