### ISSUE TITLE
Where is the DB query result from?

### ISSUE THREAD

**Issue by taolusi** [wenhuchen/HDSA-Dialog#9]
Nice work!
Where is the DB query result in train, dev, test.tsv and the source in train, val, test.json from? It seems that they are the same. 
Your paper said that the ground truth belief state and DB records are assumed available. So how to get the DB query result based on this assumption?

**Comment by wenhuchen** [comment]
Hi there, this paper does not touch the state tracking part. However, during generation, we need the DB results to do the slot filling for post-processing. Therefore, we assume the state tracking (DB constraint) is already known to us at each round and use that as the SQL query to retrieve the DB result during pre-processing. This step is handled in preprocessing/create_delex_data.py, the code is revised based on "https://github.com/budzianowski/multiwoz/blob/master/create_delex_data.py".

**Comment by taolusi** [comment]
> Hi there, this paper does not touch the state tracking part. However, during generation, we need the DB results to do the slot filling for post-processing. Therefore, we assume the state tracking (DB constraint) is already known to us at each round and use that as the SQL query to retrieve the DB result during pre-processing. This step is handled in preprocessing/create_delex_data.py, the code is revised based on "https://github.com/budzianowski/multiwoz/blob/master/create_delex_data.py".

Thank you for your reply. I still have some questions about this issue. I have studied your revised create_delex_data.py, but i cannot find how the train, dev, test.tsv files are generated. And the train, val, test.json are generated based on train, val, test.bak.json where the "source" e.g. DB query result already exits, could please share the code of generating .bak.json files since i cannot find where the dbpointer.py is used.

**Comment by taolusi** [comment]
> Hi there, this paper does not touch the state tracking part. However, during generation, we need the DB results to do the slot filling for post-processing. Therefore, we assume the state tracking (DB constraint) is already known to us at each round and use that as the SQL query to retrieve the DB result during pre-processing. This step is handled in preprocessing/create_delex_data.py, the code is revised based on "https://github.com/budzianowski/multiwoz/blob/master/create_delex_data.py".

Get it! Thank you for your reply!

**Comment by taolusi** [comment]
Sorry for another question. In create_delex_data.py, the train, val, test.json files are generated using train, val, test.bak.json files. I wonder where these bak.json files are from and what they are used for?

**Comment by wenhuchen** [comment]
Hi, the bak file is only for reusing the dialog act we defined in the previous version. It has nothing to do with the DB records, the relevant lines about the DB records are from line 202-221 from create_delex_data.py. You can specifically look into these lines to understand how it is generated.

**Comment by taolusi** [comment]
Thank you very much for your reply.
